sudo: required
dist: trusty
language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
# addons:
#   apt:
#     sources:
#       - google-chrome
#     packages:
#       - google-chrome-stable
before_install:
  - npm install -g bower
install:
  - npm install
  - bower install
# before_script:
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start
#   - npm i -g npm@^3
#   - sleep 3 # give xvfb some time to start
notifications:
  email: false
  slack:
    rooms:
      - m-wayteam:U1iFZyUui2QAUDtcbRS8ybZX#generator-m-services
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/87130ded51c12384d4e7
      - https://mattermost.mwaysolutions.com/hooks/7b794wboitdaxrzjkxcjt3enjr
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
